name: testWorkflow
run-name: workflowTesting
on: [push]
jobs:
  run-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
          node-version: '14'
      - run: node index.js
